Fix "error: implicit declaration of function `vmtruncate'"
vmtruncate was removed in kernel 3.8.0.

Patch from
http://erikbryantology.blogspot.co.uk/2013/03/patching-vmware-tools-in-fedora-18.html